version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: chat-app
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
    name: nest-db
