version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: chat-app
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
